# Generated by Django 5.0.1 on 2024-01-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocapp', '0005_alter_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
