# Generated by Django 5.0.1 on 2024-01-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocapp', '0006_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetable', 'Vegetable'), ('Fruit', 'Fruit'), ('Beverages', 'Beverages'), ('Oil&masala', 'Oil&masala'), ('Snacks', 'Snacks'), ('Egg&meat', 'Egg&meat')], default='', max_length=50),
        ),
    ]
