# Generated by Django 5.0.1 on 2024-01-21 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocapp', '0016_alter_product_instock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
