# Generated by Django 5.0.1 on 2024-01-21 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocapp', '0017_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='instock',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
